### ISSUE TITLE
1.20.1 not available on Modrinth

### ISSUE THREAD

**Issue by deepore** [great-big-world/creo-api#1]
Survivality is currently unplayable because Creo API is not available for 1.20.1 on Modrinth.

**Comment by jack-zisa** [comment]
Will be porting the API to 1.20.1 and possible some other older versions soon. Just underwent a complete refactor of the project to make it cleaner and more compatible. Survivality & Great Big World will be updated soon to match.

**Comment by jack-zisa** [comment]
There are now versions available for 1.19.4-1.20.4. Please note these won't work with Survivality since it is a completely different mod from Creo Lib.

**Comment by jack-zisa** [comment]
Survivality is now updated and will not depend on Creo API while it's being reworked.
